### PR TITLE
fix ajax

### PR DESCRIPTION
**Pull request by northdakota**
Sometimes ajax request are broked on profiled site.
So we need to disable xhprof footer link for ajax requests.

Thx.

### CODE REVIEW

**Comment by MarkRose** [comment]
This would be awful to merge, because I'm using xhprof to profile ajax requests.

**Comment by aik099** [comment]
Proposed fix doesn't disable profiling of ajax requests. It only prevents profile result viewing link from being added to ajax request output (because usually ajax requests return JSON and that link would break things).

You still can see profiler results from dashboard.

**Comment by jonursenbach** [comment]
This should probably be a config setting instead, so people who want the link in their ajax requests can have it there.

**Comment by preinheimer** [comment]
So my original solution for this problem was exception URLs 
https://github.com/preinheimer/xhprof/blob/master/external/header.php#L56
Which I recognize is very janky. 
@jonursenbach it seems like most ajax requests will break if this is appended, is reading them off the wire a common solution for you?

**Comment by jonursenbach** [comment]
@preinheimer We actually hacked it a bit in our installation to dump the XHProf link into a custom header, because yeah, you can't expect what the response is and it ends up breaking it.

**Comment by preinheimer** [comment]
@jonursenbach Cool. How about we merge this, and you throw up a nice little PR to add an "output header" option.? :smile_cat: 

You may also be interested in https://github.com/perftools/xhgui I've added a waterfall view there. to help visualize concurrent ajax requests.

**Comment by jonursenbach** [comment]
@preinheimer Sounds good. WIll submit that PR after this gets merged.

**Comment by preinheimer** [comment]
thanks @northdakota sorry this took so long.

**Pull request merged**
