### PR TITLE
Update xhprof_runs.php

### PR DESCRIPTION
**Pull request by FraGoTe**
pmu field is integer. #95

### CODE REVIEW

**Comment by aik099** [comment]
Something doesn't work without this PR for you?

**Comment by FraGoTe** [comment]
when the minimum is 0 it tries to save '' in integers fields and that makes fail the insert.

**Comment by aik099** [comment]
The INSERT of string into integer field only failed, when you're running MySQL in STRICT mode. But yes, you're right in attempting to fix that.

**Comment by aik099** [comment]
@preinheimer , PR looks good and I guess can be merged.

**Pull request merged**
