### PR TITLE
XHPROF UI Update

### PR DESCRIPTION
**Pull request by cmkshaw**
XHPROF 2.0 💃 

image

image

### CODE REVIEW

**Comment by aik099** [comment]
Can you please do screen-by-screen comparison?

**Comment by aik099** [comment]
Looking at change I'm quite impressed because changes look like custom-tailored CSS changes to get desired effect with less CSS/HTML changes. And no boiler-plate CSS/HTML.

**Comment by cmkshaw** [comment]
Some before/after images:

home

graph

desktop hd

tables

child report

**Comment by aik099** [comment]
> https://cloud.githubusercontent.com/assets/3333696/20629595/69922e7c-b2fa-11e6-8f8b-e3171acd862e.png
> https://cloud.githubusercontent.com/assets/3333696/20629596/6be41320-b2fa-11e6-95b7-89d4251dd5cf.png

This one has bugs in it:

* the table header doesn't have any specific bolded style and therefore looks like a regular row (harder to find it)
* on the left table (below `View Callgraph` link) the table border is missing; I've expected all tables to look the same in new UI, because they look the same in old UI (e.g. last table on the page have header background, but other tables on same page don't have it)

> https://cloud.githubusercontent.com/assets/3333696/20629597/6d037a98-b2fa-11e6-8366-60f027a01c44.png

Not sure why some of headings in 1st column are rights aligned when all content in that column is left aligned. In old UI all headings were centered.

**Comment by cmkshaw** [comment]
Ah, good call. Made some style adjustments (mostly to the tables) as per PR comments:

desktop hd
tables
child report

**Comment by aik099** [comment]
Much better now.

> https://cloud.githubusercontent.com/assets/3333696/20633169/aec98280-b311-11e6-8b0a-7caf4427d311.png

The Run ID was wrapped to next line. Was this change intended?

**Comment by cmkshaw** [comment]
Yeah, intended. Think it looks weird?

**Comment by aik099** [comment]
If intended, then all is fine.

**Comment by aik099** [comment]
I saw you've added some SVG files as part of this PR, so I'm guessing you know how to create SVG files.

Maybe you can help me out with #104?

**Comment by aik099** [comment]
I'll keep this PR open just in case you need to make some more changes and merge it next week.

**Comment by cmkshaw** [comment]
This is good to go! I'll take a look at #104.

**Comment by aik099** [comment]
Merging, Thanks @cmkshaw .

**Comment by aik099** [comment]
After I've tried to see how new UI looks for myself I ended up using old CSS no matter how much I've pressed F5 to reload the page.

It would be better to add some hash to CSS include on all pages to allow browser to auto-reload it.

**Pull request merged**
